### ISSUE TITLE
Matlab Engine not Installed 

### ISSUE THREAD

**Issue by jacastillo93** [Calysto/matlab_kernel#106]
Hi! 
I already ran the code suggested by mathworks: 
cd "matlabroot\extern\engines\python"
sudo python setup.py install

then installed your github repository:
pip install git+https://github.com/Calysto/matlab_kernel

And also I made sure to run over python 2.7, 3.5, 3.4 (In fact all of them have the same issue) I am running matlab 2017a. But I get this output while running my jupyter notebook : 

[W 18:37:44.485 NotebookApp] Timeout waiting for kernel_info reply from 1109222d-a7f8-4b69-85b0-e30e824046ae
[I 18:37:46.478 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 1109222d-a7f8-4b69-85b0-e30e824046ae restarted
Traceback (most recent call last):
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/matlab_kernel/__main__.py", line 3, in <module>
    MatlabKernel.run_as_main()
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/metakernel/_metakernel.py", line 115, in run_as_main
    MetaKernelApp.launch_instance(kernel_class=cls)
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 465, in initialize
    self.init_kernel()
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 376, in init_kernel
    user_ns=self.user_ns,
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/jose/anaconda3/envs/jmatlab/lib/python3.5/site-packages/matlab_kernel/kernel.py", line 68, in __init__
    """)
ImportError: 
        Matlab engine not installed:
        See https://www.mathworks.com/help/matlab/matlab-engine-for-python.htm
        
[W 18:37:49.494 NotebookApp] KernelRestarter: restart failed
[W 18:37:49.494 NotebookApp] Kernel 1109222d-a7f8-4b69-85b0-e30e824046ae died, removing from map.
kernel 1109222d-a7f8-4b69-85b0-e30e824046ae restarted failed!
[W 18:37:49.516 NotebookApp] 410 DELETE /api/sessions/74f03620-5838-4b71-9a7d-1fda1c9a8008 (127.0.0.1): Kernel deleted before session
[W 18:37:49.517 NotebookApp] Kernel deleted before session
[W 18:37:49.517 NotebookApp] 410 DELETE /api/sessions/74f03620-5838-4b71-9a7d-1fda1c9a8008 (127.0.0.1) 2.12ms referer=http://localhost:8888/notebooks/Untitled.ipynb
![screenshot from 2018-03-24 18-40-40](https://user-images.githubusercontent.com/30271807/37870784-e0006a40-2f92-11e8-9b48-ef1b050cdcc8.png)

**Comment by jacastillo93** [comment]
I know the issue is with the engine, but I have no idea how to fix it. I already tried to open the notebook in the same folder as "matlabroot\extern\engines\python" but it ain't working

**Comment by dsblank** [comment]
You have to use the same python in both cases, the setup.py, and when
running the kernel. You can see the path to python35 in the error message.
