### ISSUE TITLE
The MATLAB-Engine for Python is not support the py3.7

### ISSUE THREAD

**Issue by TerenceLiu98** [Calysto/matlab_kernel#109]
My computer is MacBook Pro and I have installed py3.7 on it. I ran the `setup.py` in this command, the computer came back with these: 
```
python python setup.py install
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    'is %s' % _version)
OSError: MATLAB Engine for Python supports Python version 2.7, 3.4, 3.5 and 3.6 but your version of Python is 3.7
```
Because I set the  `alias: python = python3.7`. 
Then, I type: `python2 setup.py install` , this time the computer says: 
```
python python2 setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/matlab
copying dist/matlab/mlarray.py -> build/lib/matlab
copying dist/matlab/__init__.py -> build/lib/matlab
copying dist/matlab/mlexceptions.py -> build/lib/matlab
creating build/lib/matlab/engine
copying dist/matlab/engine/fevalfuture.py -> build/lib/matlab/engine
copying dist/matlab/engine/matlabengine.py -> build/lib/matlab/engine
copying dist/matlab/engine/basefuture.py -> build/lib/matlab/engine
copying dist/matlab/engine/__init__.py -> build/lib/matlab/engine
copying dist/matlab/engine/matlabfuture.py -> build/lib/matlab/engine
copying dist/matlab/engine/futureresult.py -> build/lib/matlab/engine
copying dist/matlab/engine/enginehelper.py -> build/lib/matlab/engine
copying dist/matlab/engine/engineerror.py -> build/lib/matlab/engine
copying dist/matlab/engine/enginesession.py -> build/lib/matlab/engine
creating build/lib/matlab/_internal
copying dist/matlab/_internal/mlarray_sequence.py -> build/lib/matlab/_internal
copying dist/matlab/_internal/mlarray_utils.py -> build/lib/matlab/_internal
copying dist/matlab/_internal/__init__.py -> build/lib/matlab/_internal
running install_lib
creating /usr/local/Homebrew/lib/python2.7/site-packages/matlab
creating /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal
copying build/lib/matlab/_internal/mlarray_sequence.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal
copying build/lib/matlab/_internal/mlarray_utils.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal
copying build/lib/matlab/_internal/__init__.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal
copying build/lib/matlab/mlarray.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab
copying build/lib/matlab/__init__.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab
creating /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/fevalfuture.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/matlabengine.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/basefuture.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/__init__.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/matlabfuture.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/_arch.txt -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/futureresult.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/enginehelper.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/engineerror.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/engine/enginesession.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine
copying build/lib/matlab/mlexceptions.py -> /usr/local/Homebrew/lib/python2.7/site-packages/matlab
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal/mlarray_sequence.py to mlarray_sequence.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal/mlarray_utils.py to mlarray_utils.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/_internal/__init__.py to __init__.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/mlarray.py to mlarray.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/__init__.py to __init__.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/fevalfuture.py to fevalfuture.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/matlabengine.py to matlabengine.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/basefuture.py to basefuture.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/__init__.py to __init__.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/matlabfuture.py to matlabfuture.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/futureresult.py to futureresult.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/enginehelper.py to enginehelper.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/engineerror.py to engineerror.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/engine/enginesession.py to enginesession.pyc
byte-compiling /usr/local/Homebrew/lib/python2.7/site-packages/matlab/mlexceptions.py to mlexceptions.pyc
running install_egg_info
Writing /usr/local/Homebrew/lib/python2.7/site-packages/matlabengineforpython-R2017b-py2.7.egg-info
```
But when I ran the Jupyter-notebook, the Matlab-kernel is dead. 

My system version is macOS 10.14 with python 2.7 and python 3.7

**Comment by blink1073** [comment]
Hi @TerenceLiu98, are you able to run the Matlab engine outside of the kernel (in a python prompt)?  https://www.mathworks.com/help/matlab/matlab_external/start-the-matlab-engine-for-python.html

**Comment by TerenceLiu98** [comment]
Hi @blink1073 , when I use python2, it is able to run the MATLAB engine; when I tried python3.7, it failed. Here is the code I typed in the terminal: 
```
➜  ~ python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matlab.engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matlab'
>>> ^D
➜  ~ python2
Python 2.7.15 (default, Jul 10 2018, 12:31:08)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matlab.engine
>>>
```

**Comment by dsblank** [comment]
You must install the matlab engine for python for all versions of Python that you wish to use it with.

**Comment by andrewssobral** [comment]
Hi @TerenceLiu98 I have the same issue with Python 3.7 and MATLAB R2018b
How you managed to fix this issue? Thanks in advance

**Comment by ict0624** [comment]
Did you install anaconda python? If correct, refer to the procedure below.
1. Runs a command prompt with administrator privileges.
2. Switch to the virtual environment where you want to install the matlab library.
- Note that Python should be installed with version 3.6 or earlier.
- If you download version 3.7 but install it like "conda install python=3.6", version 3.6 will be installed.

3. To install the engine API, choose one of the following.
- You might need administrator privileges to execute these commands.

- At a Windows operating system prompt —
```
cd "matlabroot\extern\engines\python"
python setup.py install
```

- At a macOS or Linux operating system prompt —
```
cd "matlabroot/extern/engines/python"
python setup.py install
```

- Below is an example.
```
(base) C:\Windows\system32>conda activate envGPU

(envGPU) C:\Windows\system32>cd C:\Program Files\MATLAB\R2018b\extern\engines\python

(envGPU) C:\Program Files\MATLAB\R2018b\extern\engines\python>python setup.py install
running install
running build
running build_py
running install_lib
copying build\lib\matlab\engine\_arch.txt -> C:\Users\ict06\AppData\Local\conda\conda\envs\envGPU\Lib\site-packages\matlab\engine
running install_egg_info
Removing C:\Users\ict06\AppData\Local\conda\conda\envs\envGPU\Lib\site-packages\matlabengineforpython-R2018a-py3.6.egg-info
Writing C:\Users\ict06\AppData\Local\conda\conda\envs\envGPU\Lib\site-packages\matlabengineforpython-R2018a-py3.6.egg-info

(envGPU) C:\Program Files\MATLAB\R2018b\extern\engines\python>
```

**Comment by YSUN-coder** [comment]
> Hi @TerenceLiu98 I have the same issue with Python 3.7 (anaconda) and MATLAB R2018b
> How you managed to fix this issue? Thanks in advance

Hi, Have you fix this problem? I met the same issue.
