### ISSUE TITLE
Autocomplete not working when comment present in cell

### ISSUE THREAD

**Issue by manu080797** [Calysto/matlab_kernel#127]
If I add a comment in a cell, the autocomplete function in Jupiter notebook stops working. Pressing TAB after writing something autocompletes to the first match but it does not show other matches for the current typed text. Pressing SHIFT+TAB should show a window with a reference to the typed function. When there is no comment in the cell both keyshortcuts work well.
![Captura de Pantalla 2019-10-11 a la(s) 21 01 27](https://user-images.githubusercontent.com/25868073/66691085-606dae00-ec6a-11e9-8f7b-92d8316ba324.png)
![Captura de Pantalla 2019-10-11 a la(s) 21 01 46](https://user-images.githubusercontent.com/25868073/66691088-606dae00-ec6a-11e9-8158-06c504b42dd2.png)
 In the console I get the following error when pressing TAB in a cell with a comment:

[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 452, in inspect_request
    content.get('detail_level', 0))
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/metakernel/_metakernel.py", line 584, in do_inspect
    cursor_pos=cursor_pos)
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/metakernel/_metakernel.py", line 759, in get_help_on
    return help_magic.get_help_on(expr, level, none_on_fail, cursor_pos)
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/metakernel/magics/help_magic.py", line 109, in get_help_on
    elif not info['magic']['name']:
KeyError: 'name'

**Comment by YutaKudo** [comment]
it happened to me also.
might be this is caused by " % means magic commands in jupyter"

I'll see metakernel codes whether it's possible to avoid this error or not
