### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by RussTedrake** [Calysto/matlab_kernel#15]
Thanks for providing this tool.  I'm admittedly new to ipython, so hope this isn't a rookie mistake, but every installation attempt I've made has resulted in errors when starting up the matlab kernel.  Given a fresh (pip) install of `jupyter`, `pymatbridge`, and then `matlab_kernel`, I'm consistently seeing the output below.  Any advice would be greatly appreciated.

```
[I 06:41:04.519 NotebookApp] KernelRestarter: restarting kernel (2/5)
/usr/local/lib/python3.4/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/usr/local/lib/python3.4/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/usr/local/lib/python3.4/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
IPython: an enhanced interactive Python shell.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--no-pprint
    Disable auto pretty printing of results.
--automagic
    Turn on the auto calling of magic commands. Type %%magic at the
    IPython  prompt  for  more information.
--pdb
    Enable auto calling the pdb debugger after every exception.
--no-pdb
    Disable auto calling the pdb debugger after every exception.
--autoindent
    Turn on autoindenting.
--no-autoindent
    Turn off autoindenting.
--no-color-info
    Disable using colors for info related things.
--color-info
    IPython can display information about objects via a set of functions,
    and optionally can use colors for this, syntax highlighting
    source code and various other elements. This is on by default, but can cause
    problems with some pagers. If you see such problems, you can disable the
    colours.
--quiet
    set log level to logging.CRITICAL (minimize logging output)
--no-deep-reload
    Disable deep (recursive) reloading by default.
--matplotlib
    Configure matplotlib for interactive use with
    the default matplotlib backend.
--secure
    Use HMAC digests for authentication of messages.
    Setting this flag will generate a new UUID to use as the HMAC key.
--debug
    set log level to logging.DEBUG (maximize logging output)
--no-stdout
    redirect stdout to the null device
--pydb
    Use the third party 'pydb' package as debugger, instead of pdb.
    Requires that pydb is installed.
--no-automagic
    Turn off the auto calling of magic commands.
--no-stderr
    redirect stderr to the null device
--nosep
    Eliminate all spacing between prompts.
--init
    Initialize profile with default config files.  This is equivalent
    to running `ipython profile create <profile>` prior to startup.
--pylab
    Pre-load matplotlib and numpy for interactive use with
    the default matplotlib backend.
--pprint
    Enable auto pretty printing of results.
--no-secure
    Don't authenticate messages.
--deep-reload
    **Deprecated** Enable deep (recursive) reloading by default. IPython can use the
    deep_reload module which reloads changes in modules recursively (it
    replaces the reload() function, so you don't need to change anything to
    use it). deep_reload() forces a full reload of modules whose code may
    have changed, which the default reload() function does not.  When
    deep_reload is off, IPython will use the normal reload(), but
    deep_reload will still be available as dreload(). This feature is off
    by default [which means that you have both normal reload() and
    dreload()].
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/IPython/core/application.py", line 185, in __init__
    super(BaseIPythonApplication, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 242, in __init__
    SingletonConfigurable.__init__(self, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/configurable.py", line 74, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/traitlets/traitlets.py", line 588, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python3.4/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python3.4/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python3.4/site-packages/traitlets/traitlets.py", line 961, in validate
    self.error(obj, value)
  File "/usr/local/lib/python3.4/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'kernel_class' trait of an IPKernelApp instance must be a subclass of 'ipykernel.kernelbase.Kernel', but a value of class 'type' (i.e. <class '__main__.MatlabKernel'>) was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/site-packages/matlab_kernel-0.5-py3.4.egg/matlab_kernel.py", line 105, in <module>
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 590, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/configurable.py", line 380, in instance
    inst = cls(*args, **kwargs)
  File "<string>", line 2, in __init__
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 77, in catch_config_error
    app.print_help()
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 349, in print_help
    self.print_options()
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 320, in print_options
    self.print_alias_help()
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 284, in print_alias_help
    cls = classdict[classname]
KeyError: 'IPKernelApp'
```

**Comment by blink1073** [comment]
Hi @RussTedrake , two questions:

- How did you start the notebook?  `ipython notebook` from the command line?
- What does the following print from the command line?:

```bash
$ python -c "import IPython; print(IPython.__version__)"
```

**Comment by RussTedrake** [comment]
> How did you start the notebook? ipython notebook from the command line?
```
jupyter notebook
ipython notebook
ipython3 notebook
```
all give the same result.

> What does the following print from the command line?:
> $ python -c "import IPython; print(IPython.__version__)”

4.0.0-b1

Thanks for the help!

**Comment by blink1073** [comment]
Ah, I don't think Jupyter 4.0 is fully functional yet, last I knew there were two packages left to release.

**Comment by RussTedrake** [comment]
Great.   Thank you!  (I had trouble deciding that from the online docs.)  

It took a bit of uninstalling/reinstalling, but i'm up and running now.  Thanks again.

**Comment by blink1073** [comment]
Cheers!

**Comment by ikinsella** [comment]
Hi, I'm running into the same issue. Could you key me in to exactly what you did to resolve the issue?

**Comment by blink1073** [comment]
@ikinsella, can you try `pip install jupyter` (or `conda install jupyter` if you're using that)?

**Comment by ikinsella** [comment]
@blink1073 Great thanks! Unfortunately, the issue I was having is that pip wouldn't install any IPython previous to version 4.0. I was able to get around it by starting a fresh venv and using conda to grab ipython-notebook version 3.2.

**Comment by blink1073** [comment]
@ikinsella, glad to hear you got it sorted.

**Comment by JohnCosnett** [comment]
Hi I cannot get my matlab_kernel to startup. I am running IPython 4.1.1 Do I need to downgrade to Ipython 3 ?

**Comment by JohnCosnett** [comment]
I 10:18:01.734 NotebookApp] Kernel started: 3b186e42-df90-4a91-9348-e903bd3818d6
    /Users/johncosnett/anaconda/lib/python3.5/site-packages/IPython/nbformat.py:13:       ShimWarning: The `IPython.nbformat` package has been deprecated. You should   import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/bin/sh: matlab: command not found
