### ISSUE TITLE
Mac 10.15, matlab 2020b, python 3.8 jupyter console --kernel matlab does not work

### ISSUE THREAD

**Issue by ouboub** [Calysto/matlab_kernel#154]
HI
I have installed matlab2020b.
I used MacOS 10.15 python 3.8 to install the python engine.

       a. In /Applications/MATLAB_R2020b.app/extern/engines/python I run

       b. sudo /usr/bin/python3 setup.py install

I install the matlab_kernel
pip3 install matlab_kernel
seems fine.
Now I run 
```
jupyter console --kernel matlab
but obtain 
Traceback (most recent call last):
  File "/Users/oub/Library/Python/3.8/bin/jupyter-console", line 10, in <module>
    sys.exit(main())
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_console/app.py", line 103, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/consoleapp.py", line 343, in initialize
    self.init_kernel_manager()
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/consoleapp.py", line 295, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/manager.py", line 337, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/manager.py", line 292, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/manager.py", line 210, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/manager.py", line 114, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Users/oub/Library/Python/3.8/lib/python/site-packages/jupyter_client/kernelspec.py", line 230, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named matlab

```
what shall I do??
regards
Uwe Brauer

**Comment by ouboub** [comment]
SOLVED:
I needed to install
pip3 install --user numpy
pip3 install --user pymatbridge

then everything  was fine.

**Comment by dsblank** [comment]
Thanks for reporting what was needed to solve your issue! Will be very helpful to the next user!

**Comment by ouboub** [comment]
BTW, this is a useful link
https://blog.espci.fr/notesdegeeks/2017/12/29/matlab-notebooks-in-jupyther/
