### ISSUE TITLE
Problems with Ubuntu 16.04 and matlab 2019a (but worked before) 

### ISSUE THREAD

**Issue by ouboub** [Calysto/matlab_kernel#158]
Hi

I mentioned a similar problem with MacOS 10.15 (issue #154) but found a solution now with Ubuntu 16.04 I am puzzled. Because I swore it worked some weeks ago.

But I installed matlab 2019b which required python 3.6 but run into a lot of problems so I uninstalled python3.5 and matlab 2019b an returned to matlab 2019.

I did the following steps.

## install the matlab engine
```
cd *usr/local/MATLAB/R2019a/extern/engines/python* sudo python3.5 setup.py install
```

## install jupyter etc
```
sudo apt-get install python3-setuptools 
sudo -H python3 -m pip install jupyter 
sudo apt-get remove python3-pexpect 
sudo -H python3 -m pip install pexpect 
sudo -H python3 -m pip install matlab_ernel
```

## start the matlab engine
```
/usr/bin/python3
import matlab.engine 
eng = matlab.engine.start_matlab()
```

## run the test
```
jupyter-console &#x2013;kernel matlab   
```

## error message is
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>core</sub>/application.py", line 266, in launch<sub>instance</sub>
    return super(JupyterApp, cls).launch<sub>instance</sub>(argv=argv, \*\*kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch<sub>instance</sub>
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch<sub>config</sub><sub>error</sub>
    return method(app, \*args, \*\*kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>console</sub>/app.py", line 141, in initialize
    self.init<sub>shell</sub>()
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>console</sub>/app.py", line 109, in init<sub>shell</sub>
    JupyterConsoleApp.initialize(self)
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>client</sub>/consoleapp.py", line 334, in initialize
    self.init<sub>kernel</sub><sub>manager</sub>()
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>client</sub>/consoleapp.py", line 288, in init<sub>kernel</sub><sub>manager</sub>
    self.kernel<sub>manager.start</sub><sub>kernel</sub>(\*\*kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>client</sub>/manager.py", line 246, in start<sub>kernel</sub>
    kernel<sub>cmd</sub> = self.format<sub>kernel</sub><sub>cmd</sub>(extra<sub>arguments</sub>=extra<sub>arguments</sub>)
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>client</sub>/manager.py", line 170, in format<sub>kernel</sub><sub>cmd</sub>
    cmd = self.kernel<sub>spec.argv</sub> + extra<sub>arguments</sub>
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>client</sub>/manager.py", line 82, in kernel<sub>spec</sub>
    self.<sub>kernel</sub><sub>spec</sub> = self.kernel<sub>spec</sub><sub>manager.get</sub><sub>kernel</sub><sub>spec</sub>(self.kernel<sub>name</sub>)
  File "/usr/local/lib/python3.5/dist-packages/jupyter<sub>client</sub>/kernelspec.py", line 236, in get<sub>kernel</sub><sub>spec</sub>
    raise NoSuchKernel(kernel<sub>name</sub>)
jupyter<sub>client.kernelspec.NoSuchKernel</sub>: No such kernel named matlab
```

any help is strongly appreciated
Uwe Brauer

**Comment by ouboub** [comment]
Some news, I run
```
sudo -H pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
```
and now I obtain
```
jupyter --kernel matlab
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-matlab` not found.
```

what is wrong now?

**Comment by ouboub** [comment]
I think I solved it (almost) it was quite an ordeal, I have to say
here is what I did 

# reinstall jupyter
```
sudo dpkg --purge python3-ptyprocess
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir jupyter
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir numpy
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir pymatbridge
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir matlab<sub>kernel</sub>
```

# check <https://github.com/Calysto/matlab_kernel#kernel-times-out-while-starting>
```
python3 -m matlab_kernel.check 
```
That told me to look for a matlab solution


# matlab solution for Ubuntu 16.04

<https://de.mathworks.com/matlabcentral/answers/403561-import-error-matlab-engine-in-python>


## solve the gcc library problem
```
LD<sub>LIBRARY</sub><sub>PATH</sub>=/usr/local/lib64/:$LD<sub>LIBRARY</sub><sub>PATH</sub>
$ export LD<sub>LIBRARY</sub><sub>PATH</sub>
$ sudo apt-add-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install gcc-6 g++-6
```

## install the engine again
```
cd usr/local/MATLAB/R2019a/extern/engines/python
sudo /usr/bin/python3 setup.py install
```

## Start the engine
 now it works, however 
```jupyter --kernel matlab
```
still gives
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-matlab` not found.
```
but I can live with that
if somebody can tell me about the last error it owuld be nice but then it works for me (for the moment) so it be ok to close the issue, but then I am not sure
