### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by fakufaku** [Calysto/matlab_kernel#18]
Hi,

I have an issue with matlab_kernel failing to install with some obscure error. 

```
File "/private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel/setup.py", line 19, in run
      from metakernel.utils import install_spec
  ImportError: cannot import name install_spec
```
Here is the full output.
```
icdhcp-1-220:MEMS_Array scheibler$ pip install matlab_kernel
Collecting matlab-kernel
  Using cached matlab_kernel-0.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.9 in /Users/scheibler/anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): pymatbridge in /Users/scheibler/anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in /Users/scheibler/anaconda/lib/python2.7/site-packages (from matlab-kernel)
Building wheels for collected packages: matlab-kernel
  Running setup.py bdist_wheel for matlab-kernel
  Complete output from command /Users/scheibler/anaconda/bin/python -c "import setuptools;__file__='/private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/tmpHj4YMCpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying matlab_kernel.py -> build/lib
  installing to build/bdist.macosx-10.5-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.5-x86_64
  creating build/bdist.macosx-10.5-x86_64/wheel
  copying build/lib/matlab_kernel.py -> build/bdist.macosx-10.5-x86_64/wheel
  running install_egg_info
  running egg_info
  creating matlab_kernel.egg-info
  writing requirements to matlab_kernel.egg-info/requires.txt
  writing matlab_kernel.egg-info/PKG-INFO
  writing top-level names to matlab_kernel.egg-info/top_level.txt
  writing dependency_links to matlab_kernel.egg-info/dependency_links.txt
  writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'matlab_kernel.egg-info/SOURCES.txt'
  writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
  Copying matlab_kernel.egg-info to build/bdist.macosx-10.5-x86_64/wheel/matlab_kernel-0.6-py2.7.egg-info
  /Users/scheibler/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
    "You should import from ipykernel or jupyter_client instead.", ShimWarning)
  /Users/scheibler/anaconda/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
    "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel/setup.py", line 51, in <module>
      'Topic :: System :: Shells',
    File "/Users/scheibler/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Users/scheibler/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Users/scheibler/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/scheibler/anaconda/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 211, in run
      self.run_command('install')
    File "/Users/scheibler/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Users/scheibler/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel/setup.py", line 19, in run
      from metakernel.utils import install_spec
  ImportError: cannot import name install_spec
  
  ----------------------------------------
  Failed building wheel for matlab-kernel
Failed to build matlab-kernel
Installing collected packages: matlab-kernel
  Running setup.py install for matlab-kernel
    Complete output from command /Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-Zz66kJ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running install_lib
    copying build/lib/matlab_kernel.py -> /Users/scheibler/anaconda/lib/python2.7/site-packages
    byte-compiling /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel.py to matlab_kernel.pyc
    error: [Errno 13] Permission denied: '/Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel.pyc'
    
    ----------------------------------------
Command "/Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-Zz66kJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T/pip-build-HLOoCa/matlab-kernel
```
I'm not sure if there is some package manager problems going on, so here is the list of packages installed. I use anaconda distribution.

```
# packages in environment at /Users/scheibler/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
accelerate                1.11.0              np19py27_p0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
appscript                 1.0.1                    py27_0  
apptools                  4.2.1                    py27_0  
argcomplete               0.8.9                    py27_0  
astropy                   1.0.3                np19py27_0  
atom                      0.3.9                    py27_0  
autopep8                  1.0.3                     <pip>
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
basemap                   1.0.7                np17py27_0  
bash-kernel               0.4                       <pip>
bcolz                     0.9.0                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py27_0  
biopython                 1.63                 np18py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.6.3                np19py27_0  
blaze-core                0.8.0                np19py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.9.0                np19py27_0  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
casuarius                 1.1                      py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.1.0                    py27_0  
chaco                     4.4.1                np19py27_0  
cheetah                   2.4.4                    py27_0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.16.0                   py27_0  
conda-build               1.12.0                   py27_0  
conda-env                 2.4.2                    py27_0  
configobj                 5.0.6                    py27_0  
cryptography              0.9.1                    py27_0  
cubes                     0.10.2                   py27_4  
cudatoolkit               6.0                          p0  
curl                      7.43.0                        0  
cvxopt                    1.1.6                     <pip>
cvxpy                     0.2                       <pip>
cython                    0.22.1                   py27_0  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.5                np19py27_0  
dateutil                  2.1                      py27_2  
decorator                 4.0.2                    py27_0  
distribute                0.6.45                   py27_0  
django                    1.7.3                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
ecdsa                     0.11                      <pip>
ecos                      1.0.3                     <pip>
enable                    4.3.0                np19py27_2  
enaml                     0.9.8                    py27_0  
enum34                    1.0.4                    py27_0  
envisage                  4.4.0                    py27_1  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
future                    0.13.1                   py27_0  
futures                   2.2.0                    py27_0  
geos                      3.3.3                         0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
gevent-zeromq             0.2.2                     <pip>
gevent_zeromq             0.2.5                    py27_3  
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      1  
idna                      2.0                      py27_0  
imaging                   1.1.7                    py27_2  
iopro                     1.6.7               np19py27_p0  
ipaddress                 1.0.7                    py27_0  
iptools                   0.6.1                     <pip>
ipykernel                 4.0.3                     <pip>
ipython                   4.0.0                    py27_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          3.2.1                    py27_0  
ipython-qtconsole         3.2.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.0.2                     <pip>
iso8601                   0.1.10                    <pip>
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            1  
jsonschema                2.4.0                    py27_0  
jupyter                   1.0.0                     <pip>
jupyter-client            4.0.0                     <pip>
jupyter-console           4.0.0                     <pip>
jupyter-core              4.0.4                     <pip>
keyring                   3.3                      py27_0  
kiwisolver                0.1.3                    py27_0  
launcher                  1.0.0                         3  
lcms                      1.19                          0  
libdynd                   0.6.5                         0  
libevent                  2.0.20                        1  
libnetcdf                 4.2.1.1                       2  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvm                      3.3                           0  
llvmlite                  0.5.0                    py27_0  
llvmmath                  0.1.1                np17py27_2  
llvmpy                    0.12.7                   py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_2  
mayavi                    4.3.1                np18py27_0  
mdp                       3.3                  np18py27_0  
meta                      0.4.2.dev                py27_0  
metakernel                0.9.0                     <pip>
mistune                   0.7                      py27_0  
mkl                       11.1                np19py27_p3  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py27_p1  
mklfft                    2.0                 np19py27_p0  
mock                      1.0.1                    py27_0  
multipledispatch          0.4.7                    py27_0  
nbconvert                 4.0.0                     <pip>
nbformat                  4.0.0                     <pip>
netcdf4                   1.0.8                np18py27_0  
networkx                  1.9.1                    py27_0  
nltk                      3.0.3                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
notebook                  4.0.4                     <pip>
numba                     0.19.1               np19py27_0  
numbapro                  0.18.0              np19py27_p2  
numbapro_cudalib          0.2                           0  
numexpr                   2.4.3               np19py27_p0  [mkl]
numpy                     1.9.2                   py27_p0  [mkl]
odo                       0.3.2                np19py27_0  
opencv                    2.4.8                np17py27_2  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.1k                        1  
optcomplete-1.2           devel                     <pip>
pandas                    0.16.2               np19py27_0  
paramiko                  1.15.2                    <pip>
path.py                   7.6                      py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pil                       1.1.7                    py27_2  
pillow                    2.8.2                    py27_0  
pip                       7.1.0                    py27_1  
ply                       3.6                      py27_0  
psutil                    2.2.1                    py27_0  
psycopg2                  2.5.3                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pyface                    4.4.0                    py27_0  
pyflakes                  0.9.2                    py27_0  
pyglet                    1.1.4                     <pip>
pygments                  2.0.2                    py27_0  
pykit                     0.2.0                np18py27_0  
pymatbridge               0.5.2                     <pip>
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
pysal                     1.6.0                np18py27_1  
pysam                     0.6                      py27_0  
pyserial                  2.7                       <pip>
pyside                    1.1.2                    py27_1  
pytables                  3.2.0                np19py27_0  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qrcode                    4.0.1.post0               <pip>
qt                        4.8.6                         3  
qtconsole                 4.0.1                     <pip>
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.7.0                    py27_0  
rope                      0.9.4                    py27_1  
rpy2                      2.3.9                     <pip>
runipy                    0.1.3                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1              np19py27_p0  [mkl]
scikits.audiolab          0.11.0                    <pip>
scikits.samplerate        0.3.3                     <pip>
scipy                     0.15.1              np19py27_p0  [mkl]
scp                       0.8.0                     <pip>
scs                       1.0.3                     <pip>
setuptools                18.1                     py27_0  
shiboken                  1.1.2                    py27_0  
simplegeneric             0.8.1                    py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.5.2                  py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                1.0.5                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
starcluster               0.95.6                    <pip>
statsmodels               0.6.1                np19py27_0  
sympy                     0.7.6                    py27_0  
tables                    3.2.0                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py27_0  
tornado                   4.2.1                    py27_0  
traitlets                 4.0.0                    py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
unidecode                 0.4.14                    <pip>
vtk                       5.10.1                   py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.24.0                   py27_0  
workerpool                0.9.2                     <pip>
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.7.3                    py27_0  
xlwings                   0.3.5                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```
Thanks a lot!

**Comment by blink1073** [comment]
Does `from metakernel.utils import install_spec` work from a python prompt?

**Comment by blink1073** [comment]
No, I see the error now, I was using an unreleased version of `metakernel`.  I bumped the versions of `metakernel` and this library, please try installing again.

**Comment by fakufaku** [comment]
Thanks for the prompt reply! I have first updated metakernel to 0.10.0 and this is the output from trying to install matlab_kernel 0.6.1:

```
icdhcp-1-220:~ scheibler$ sudo -H pip install --no-cache-dir  matlab_kernel
Collecting matlab-kernel
  Downloading matlab_kernel-0.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.10 in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): pymatbridge in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Installing collected packages: matlab-kernel
  Running setup.py install for matlab-kernel
    Complete output from command /Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-9lL7dI/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ziCwuE-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying matlab_kernel.py -> build/lib
    running install_lib
    copying build/lib/matlab_kernel.py -> /Users/scheibler/anaconda/lib/python2.7/site-packages
    byte-compiling /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel.py to matlab_kernel.pyc
    running install_egg_info
    running egg_info
    creating matlab_kernel.egg-info
    writing requirements to matlab_kernel.egg-info/requires.txt
    writing matlab_kernel.egg-info/PKG-INFO
    writing top-level names to matlab_kernel.egg-info/top_level.txt
    writing dependency_links to matlab_kernel.egg-info/dependency_links.txt
    writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    Copying matlab_kernel.egg-info to /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel-0.6.1-py2.7.egg-info
    writing list of installed files to '/tmp/pip-ziCwuE-record/install-record.txt'
    /Users/scheibler/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
      "You should import from ipykernel or jupyter_client instead.", ShimWarning)
    Installing kernel spec
    error: [Errno 2] No such file or directory: '/Users/scheibler/anaconda/lib/python2.7/site-packages/metakernel/images/logo-64x64.png'
    
    ----------------------------------------
Command "/Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-9lL7dI/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ziCwuE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-9lL7dI/matlab-kernel
```
When metakernel is installed, I have spotted that the logo files are installed at the following location:
```
/Users/scheibler/anaconda/metakernel/images/logo-32x32.png
/Users/scheibler/anaconda/metakernel/images/logo-64x64.png
```
That is, at the root of the anaconda folder, and not the site-packages folder.

**Comment by blink1073** [comment]
Apologies, can you try again?

**Comment by fakufaku** [comment]
Still the same error:
```
icdhcp-1-220:~ scheibler$ sudo -H pip install --no-cache-dir  metakernel
Collecting metakernel
  Downloading metakernel-0.10.1-py2.py3-none-any.whl (110kB)
    100% |████████████████████████████████| 114kB 257kB/s 
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in ./anaconda/lib/python2.7/site-packages (from metakernel)
Installing collected packages: metakernel
Successfully installed metakernel-0.10.1
icdhcp-1-220:~ scheibler$ sudo -H pip install --no-cache-dir  matlab_kernel
Collecting matlab-kernel
  Downloading matlab_kernel-0.6.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.10.1 in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): pymatbridge in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Installing collected packages: matlab-kernel
  Running setup.py install for matlab-kernel
    Complete output from command /Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-R9xV6C/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pQzceq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying matlab_kernel.py -> build/lib
    running install_lib
    copying build/lib/matlab_kernel.py -> /Users/scheibler/anaconda/lib/python2.7/site-packages
    byte-compiling /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel.py to matlab_kernel.pyc
    running install_egg_info
    running egg_info
    creating matlab_kernel.egg-info
    writing requirements to matlab_kernel.egg-info/requires.txt
    writing matlab_kernel.egg-info/PKG-INFO
    writing top-level names to matlab_kernel.egg-info/top_level.txt
    writing dependency_links to matlab_kernel.egg-info/dependency_links.txt
    writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    Copying matlab_kernel.egg-info to /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel-0.6.2-py2.7.egg-info
    writing list of installed files to '/tmp/pip-pQzceq-record/install-record.txt'
    /Users/scheibler/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
      "You should import from ipykernel or jupyter_client instead.", ShimWarning)
    Installing kernel spec
    error: [Errno 2] No such file or directory: '/Users/scheibler/anaconda/lib/python2.7/site-packages/metakernel/images/logo-64x64.png'
    
    ----------------------------------------
Command "/Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-R9xV6C/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pQzceq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-R9xV6C/matlab-kernel
```

**Comment by blink1073** [comment]
Argh, I bumped it again if you wouldn't mind another round.

**Comment by fakufaku** [comment]
I keep getting the same result (but I see the version number going up):
```
icdhcp-1-220:~ scheibler$ sudo -H pip install --no-cache-dir  metakernel
Collecting metakernel
  Downloading metakernel-0.10.2-py2.py3-none-any.whl (110kB)
    100% |████████████████████████████████| 114kB 583kB/s 
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in ./anaconda/lib/python2.7/site-packages (from metakernel)
Installing collected packages: metakernel
Successfully installed metakernel-0.10.2
icdhcp-1-220:~ scheibler$ sudo -H pip install --no-cache-dir  matlab_kernel
Collecting matlab-kernel
  Downloading matlab_kernel-0.6.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.10.2 in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): pymatbridge in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in ./anaconda/lib/python2.7/site-packages (from matlab-kernel)
Installing collected packages: matlab-kernel
  Running setup.py install for matlab-kernel
    Complete output from command /Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-FfmbfU/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RBncYR-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying matlab_kernel.py -> build/lib
    running install_lib
    copying build/lib/matlab_kernel.py -> /Users/scheibler/anaconda/lib/python2.7/site-packages
    byte-compiling /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel.py to matlab_kernel.pyc
    running install_egg_info
    running egg_info
    creating matlab_kernel.egg-info
    writing requirements to matlab_kernel.egg-info/requires.txt
    writing matlab_kernel.egg-info/PKG-INFO
    writing top-level names to matlab_kernel.egg-info/top_level.txt
    writing dependency_links to matlab_kernel.egg-info/dependency_links.txt
    writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    writing manifest file 'matlab_kernel.egg-info/SOURCES.txt'
    Copying matlab_kernel.egg-info to /Users/scheibler/anaconda/lib/python2.7/site-packages/matlab_kernel-0.6.3-py2.7.egg-info
    writing list of installed files to '/tmp/pip-RBncYR-record/install-record.txt'
    /Users/scheibler/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
      "You should import from ipykernel or jupyter_client instead.", ShimWarning)
    Installing kernel spec
    error: [Errno 2] No such file or directory: '/Users/scheibler/anaconda/lib/python2.7/site-packages/metakernel/images/logo-64x64.png'
    
    ----------------------------------------
Command "/Users/scheibler/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-FfmbfU/matlab-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RBncYR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-FfmbfU/matlab-kernel
```
Am I doing something wrong ?

**Comment by fakufaku** [comment]
I am not sure how the setup.py works, but there might be a discrepancy between the location of the logo files in metakernel's `setup.py` and `metakernel.utils.install_kernel_resources`:

https://github.com/Calysto/metakernel/blob/master/metakernel/utils/kernel.py#L8
https://github.com/Calysto/metakernel/blob/master/setup.py#L33

**Comment by blink1073** [comment]
I found a way to work around it for now.  I was able to `pip install matlab_kernel` from a clean conda environment with the latest version.

**Comment by fakufaku** [comment]
It worked this time. Fantastic. Thanks for your help!

**Comment by blink1073** [comment]
Cheers!  Thanks for the diagnostics and the error report!
