### ISSUE TITLE
Matlab kernel runs error when execute command in notebook

### ISSUE THREAD

**Issue by foxlog** [Calysto/matlab_kernel#30]
when run command in notebook, error appears as follow:

[I 09:14:10.337 NotebookApp] Kernel started: 90ca2060-fa07-479e-9d64-06e7b71f787f
/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 212, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 370, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/metakernel/_metakernel.py", line 337, in do_execute
    retval = self.do_execute_direct(code)
  File "/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matlab_kernel/kernel.py", line 39, in do_execute_direct
    self._matlab.run_code(fig_code)
  File "/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pymatbridge/pymatbridge.py", line 319, in run_code
    return self.run_func('evalin', 'base', code, nargout=0)
  File "/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pymatbridge/pymatbridge.py", line 295, in run_func
    raise ValueError('Session not started, use start()')
ValueError: Session not started, use start()

following check is ok:
from pymatbridge import Matlab
mlab = Matlab(r'/Applications/MATLAB_R2014b.app/bin/matlab)
mlab.start()
print(mlab.run_code('a=1;'))

pip install -U matlab_kernel : 

Requirement already satisfied (use --upgrade to upgrade): matlab-kernel in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): pymatbridge in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.10.5 in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): pexpect in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): gnureadline in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): appnope in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): path.py in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from pickleshare->IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from traitlets->IPython>=3.0->metakernel>=0.10.5->matlab-kernel)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from pexpect->IPython>=3.0->metakernel>=0.10.5->matlab-kernel)

**Comment by blink1073** [comment]
Hi @foxlog, I just released a new version which should fix that, please try `pip install -U matlab_kernel; python -m matlab_kernel.install`.

**Comment by blink1073** [comment]
Closing due to inactivity, please reopen if you still see a problem on the latest release.
