### ISSUE TITLE
Timeout waiting for kernel_info reply from ...

### ISSUE THREAD

**Issue by JohnCosnett** [Calysto/matlab_kernel#34]
The matlab kernel is selectable in the jupyter "new" menu but doesn't work.

I have no previous experience with `pymatbridge` perhaps I have missed something trivial?
I already have been using MATLAB_R2015a desktop for a month it is stored at:
> /Applications/MATLAB_R2015a.app/bin/matlab

    Timeout waiting for kernel_info reply from cee4f722-1bec-4f98-8114-2866828e327c

OSX 10.10.5
python 3.4
Ipython 4.1.1
pymatbridge 0.5.2 ioos
jupyter 1.0.0
MATLAB_R2015a 
Conda for my dependencies!

-----
    pip install matlab_kernel
    python -m matlab_kernel.install

    export MATLAB_EXECUTABLE=/Applications/MATLAB_2015a.app/bin/matlab
    jupyter notebook --kernel=matlab_kernel

-----

I get this error first:
         ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.

![screen shot 2016-02-28 at 14 00 43](https://cloud.githubusercontent.com/assets/15061801/13379658/d3b8a38c-de23-11e5-98fe-fdfcd152f33f.png)

here is a copyable version:

------

(root)Johns-iMac:bin johncosnett$ jupyter notebook --kernel=matlab_kernel
[W 13:59:45.335 NotebookApp] Unrecognized alias: '--kernel=matlab_kernel', it will probably have no effect.
[I 13:59:45.576 NotebookApp] The port 8888 is already in use, trying another random port.
[I 13:59:45.581 NotebookApp] Serving notebooks from local directory: /Applications/MATLAB_R2015a.app/bin
[I 13:59:45.581 NotebookApp] 0 active kernels 
[I 13:59:45.581 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
[I 13:59:45.581 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:59:45.661 NotebookApp] Saving file at /Untitled1.ipynb
[I 13:59:52.405 NotebookApp] Creating new notebook in 
[I 13:59:52.793 NotebookApp] Kernel started: cee4f722-1bec-4f98-8114-2866828e327c
/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/bin/sh: /usr/bin/matlab: No such file or directory
[W 14:00:02.854 NotebookApp] Timeout waiting for kernel_info reply from cee4f722-1bec-4f98-8114-2866828e327c
Traceback (most recent call last):
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/matlab_kernel/__main__.py", line 6, in <module>
    IPKernelApp.launch_instance(kernel_class=MatlabKernel)
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/matlab_kernel/kernel.py", line 35, in __init__
    self._matlab.start()
  File "/Users/johncosnett/anaconda/envs/ipython3.0.0/lib/python3.4/site-packages/pymatbridge/pymatbridge.py", line 225, in start
    raise ValueError("%s failed to start" % self._program_name())
ValueError: MATLAB failed to start

**Comment by JohnCosnett** [comment]
SOLVED
========
just by pasting this into terminal and restarting :)

    echo “export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab” >> ~/.bash_profile

**Comment by dsblank** [comment]
Great! Glad you got it figured out.
