### ISSUE TITLE
Error at python -m matlab_kernel install

### ISSUE THREAD

**Issue by TiemenSch** [Calysto/matlab_kernel#82]
Sadly, I cannot get the MATLAB kernel to work. I have the following installation:
* Windows 10
* MATLAB 2016b (I ran the extern/engines/python/setup.py) 
* Miniconda3
* pip install matlab_kernel
* python -m matlab_kernel install

I'm getting the following error on that final command: 
```
Traceback (most recent call last):
  File "C:\Users\Tiemen\Miniconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Tiemen\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tiemen\Miniconda3\lib\site-packages\matlab_kernel\__main__.py", line 2, in <module>
    from .kernel import MatlabKernel
  File "C:\Users\Tiemen\Miniconda3\lib\site-packages\matlab_kernel\kernel.py", line 15, in <module>
    from .wurlitzer import Wurlitzer
  File "C:\Users\Tiemen\Miniconda3\lib\site-packages\matlab_kernel\wurlitzer.py", line 15, in <module>
    from fcntl import fcntl, F_GETFL, F_SETFL
ImportError: No module named 'fcntl'
```
I tried to look for a module **fcntl** on the web, pip and conda, but all I can find is that it's Linux only.

Any ideas?

**Comment by blink1073** [comment]
This should be fixed by upgrading to v0.13: `pip install -U matlab_kernel`.

**Comment by TiemenSch** [comment]
Worked like a charm, thanks!

**Comment by blink1073** [comment]
:boom:
