### ISSUE TITLE
No module named matlab_kernel

### ISSUE THREAD

**Issue by leewujung** [Calysto/matlab_kernel#84]
Help!! I am stuck at the step of doing `python -m matlab_kernel install`. I am on Ubuntu 14.04 LTS.

Using `$ pip install matlab_kernel` I got the following:
```
Requirement already satisfied: matlab_kernel in ./anaconda3/lib/python3.5/site-packages
Requirement already satisfied: ipython>=4.0.0 in ./anaconda3/lib/python3.5/site-packages (from matlab_kernel)
Requirement already satisfied: metakernel>=0.18.0 in ./anaconda3/lib/python3.5/site-packages (from matlab_kernel)
Requirement already satisfied: backports.tempfile in ./anaconda3/lib/python3.5/site-packages (from matlab_kernel)
Requirement already satisfied: jupyter-client>=4.4.0 in ./anaconda3/lib/python3.5/site-packages (from matlab_kernel)
Requirement already satisfied: pathlib in ./anaconda3/lib/python3.5/site-packages (from matlab_kernel)
Requirement already satisfied: pexpect>=4.2 in ./anaconda3/lib/python3.5/site-packages (from metakernel>=0.18.0->matlab_kernel)
Requirement already satisfied: backports.weakref in ./anaconda3/lib/python3.5/site-packages (from backports.tempfile->matlab_kernel)
Requirement already satisfied: ptyprocess>=0.5 in ./anaconda3/lib/python3.5/site-packages (from pexpect>=4.2->metakernel>=0.18.0->matlab_kernel)
```
But when I did `python -m matlab_kernel install` I got
```
/usr/bin/python: No module named matlab_kernel
```
Am I missing something?
Thanks!

**Comment by blink1073** [comment]
Hi @leewujung, it pip is using a conda environment, while `python` is using your system python.  You can verify with `which python` and `which pip`.  You most likely need to prepend the anaconda path to your PATH in your `~/.bashrc`.

**Comment by leewujung** [comment]
Ok, I found out that I was using `sudo python` which goes to /usr/bin/python instead of the anaconda path. Now I get a different type of error:
```
(py35) wu-jung@wujung-Precision-Tower-3620:~/internal_2tb/MATLAB/2016b/extern/engines/python$ python -m matlab_kernel install
Traceback (most recent call last):
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/matlab/engine/__init__.py", line 42, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'matlabengineforpython3_5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/matlab/engine/__init__.py", line 58, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/wu-jung/internal_2tb/MATLAB/2016b/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libmx.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/matlab_kernel/__main__.py", line 2, in <module>
    from .kernel import MatlabKernel
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/matlab_kernel/kernel.py", line 22, in <module>
    import matlab.engine
  File "/home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/matlab/engine/__init__.py", line 61, in <module>
    'MathWorks Technical Support for assistance: %s' % e)
OSError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: /home/wu-jung/anaconda3/envs/py35/lib/python3.5/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/wu-jung/internal_2tb/MATLAB/2016b/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libmx.so)
```
I tried `conda install libgcc` but it didn't seem to change anything.

**Comment by leewujung** [comment]
It turns out the problem can be solved by copying `libstdc++` in matlab to the lib directory in anaconda. There it has the right version of `CXXABI_1.3.8` the installer asked for. Not sure why this wasn't a problem when I did it on a Mac.

**Comment by blink1073** [comment]
Glad you got sorted.  Thank you for posting the solution as well.
