### ISSUE TITLE
TemporaryDirectory error when using plot

### ISSUE THREAD

**Issue by s3vinci** [Calysto/matlab_kernel#87]
Hi, I have just installed matlab_kernel with jupyter and was following a tutorial. Everything seems to be up to date and working on OSX but when I use plot I get the following error (everything else works)

[W 20:05:20.237 NotebookApp] Timeout waiting for kernel_info reply from fa5af273-3d7f-4b34-8a0b-51df2901e06d
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Library/Python/2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/Library/Python/2.7/site-packages/metakernel/_metakernel.py", line 357, in do_execute
    retval = self.do_execute_direct(code)
  File "/Library/Python/2.7/site-packages/matlab_kernel/kernel.py", line 92, in do_execute_direct
    with TemporaryDirectory() as tmpdir:
NameError: global name 'TemporaryDirectory' is not defined

Any idea on how I could solve this problem?

**Comment by s3vinci** [comment]
I solved the problem

try:
    from tempfile import TemporaryDirectory
except ImportError:
    from backports import tempfile

line 93
TemporaryDirectory() as tmpdir:

is not going to work if the first import didn't work and you used the second
"from backports  import tempfile"
If this gets triggered then line 93 should be
tempfile.TemporaryDirectory()

Very happy now..

**Comment by blink1073** [comment]
Thanks!  Fixed in 0.13.2.
