### ISSUE TITLE
Hangs when there is large output to print

### ISSUE THREAD

**Issue by jayendra13** [Calysto/matlab_kernel#99]
I am using `matlab_kernel` with `MATLAB-7.5.0` installed on `Ubuntu-16.04 LTS`. The kernel hangs in the case when it has to print a large amount of text.

```
jupyter console --kernel matlab

Matlab Kernel


In [1]: disp('hello')
      : 
Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge-22cf8e23-9d4c-4136-a9b5-dd4030643081
Send 'exit' command to kill the server
.MATLAB started and connected!
hello

In [2]: for i=1:100 disp('hello'); end
hello
hello
hello
...

In [3]: for i=1:100 A(1:999)='A';disp(A); end
```

After Third input it becomes unresponsive and When I press `CTRL+C` I get the following traceback.

```
^CERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
File "/home/user2/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
callback(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
handler(stream, idents, msg)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
user_expressions, allow_stdin)
File "/usr/local/lib/python2.7/dist-packages/metakernel/_metakernel.py", line 357, in do_execute
retval = self.do_execute_direct(code)
File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/kernel.py", line 127, in do_execute_direct
resp = self._matlab.run_code(code.strip())
File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/kernel.py", line 52, in run_code
return self._engine.run_code(code)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 319, in run_code
return self.run_func('evalin', 'base', code, nargout=0)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 309, in run_func
nargout=nargout)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 272, in _json_response
return json.loads(self._response(**kwargs), object_hook=decode_pymat)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 230, in _response
resp = self.socket.recv_string()
File "/home/user2/.local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 457, in recv_string
msg = self.recv(flags=flags)
File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
PyErr_CheckSignals()
KeyboardInterrupt
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
File "/home/user2/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
self._handle_recv()
File "/home/user2/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
self._run_callback(callback, msg)
File "/home/user2/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
callback(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
handler(stream, idents, msg)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
user_expressions, allow_stdin)
File "/usr/local/lib/python2.7/dist-packages/metakernel/_metakernel.py", line 357, in do_execute
retval = self.do_execute_direct(code)
File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/kernel.py", line 127, in do_execute_direct
resp = self._matlab.run_code(code.strip())
File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/kernel.py", line 52, in run_code
return self._engine.run_code(code)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 319, in run_code
return self.run_func('evalin', 'base', code, nargout=0)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 309, in run_func
nargout=nargout)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 272, in _json_response
return json.loads(self._response(**kwargs), object_hook=decode_pymat)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 230, in _response
resp = self.socket.recv_string()
File "/home/user2/.local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 457, in recv_string
msg = self.recv(flags=flags)
File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
PyErr_CheckSignals()
KeyboardInterrupt
^CError in sys.exitfunc:
Traceback (most recent call last):
File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
func(*targs, **kargs)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 239, in stop
if self._response(cmd='exit') == "exit":
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 229, in _response
self.socket.send_string(req)
File "/home/user2/.local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 438, in send_string
return self.send(u.encode(encoding), flags=flags, copy=copy)
File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7305)
File "zmq/backend/cython/socket.pyx", line 683, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7048)
File "zmq/backend/cython/socket.pyx", line 206, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:3032)
File "zmq/backend/cython/socket.pyx", line 201, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2920)
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
raise ZMQError(errno)
ZMQError: Operation cannot be accomplished in current state
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
func(*targs, **kargs)
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 239, in stop
if self._response(cmd='exit') == "exit":
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 229, in _response
self.socket.send_string(req)
File "/home/user2/.local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 438, in send_string
return self.send(u.encode(encoding), flags=flags, copy=copy)
File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7305)
File "zmq/backend/cython/socket.pyx", line 683, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:7048)
File "zmq/backend/cython/socket.pyx", line 206, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:3032)
File "zmq/backend/cython/socket.pyx", line 201, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2920)
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
raise ZMQError(errno)
ZMQError: Operation cannot be accomplished in current state
```

**Comment by blink1073** [comment]
Hi @jayendra13, it looks like you're using an older version of this kernel that used `pymatbridge`.  Are you able to upgrade?

**Comment by jayendra13** [comment]
Yes, I don't have an option other than using `pymatbridge`. The latest engine I think uses the `python-engine` provided my matlab, which I can't use with my older version of matlab(7.5). 
If it is a known issue can you provide me pointers I can try to investigate.

**Comment by blink1073** [comment]
In general that much text output won't be handled well by a Jupyter frontend, I think the issue here is that kernel interrupt behavior was not properly implemented in the version of the kernel you are using.
